
spring:
  elasticsearch:
    cluster-name:
    rest:
      uri: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user

jwt:
  secret: fdag32fdsavv32few89vbbafdsbaugubdsag8904fdsafdvcxcbre
  expiration: 25920000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uui}
server:
  port: 8089

logging:
  level:
    org.springframework.security: trace
    com.example.auth: info
