
spring:
  elasticsearch:
    cluster-name:
    rest:
      uri: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/user_blogs?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: user

token:
  secret: ssssssssssssssssssssssssssmmmmmmmmmmmmmmm
  expiration: 600000

