spring:
  elasticsearch:
    cluster-name:
    rest:
      uris: http://localhost:8080
  datasource:
    url: jdbc:mysql://localhost:3306/post?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

token:
  secret: ssssssssssssssssssssssssssmmmmmmmmmmmmmmm
  expiration: 600000


