spring:
  elasticsearch:
    cluster-name:
    rest:
      uris: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/post?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: post
  kafka:
    bootstrap-servers: 192.168.0.12:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: post
      auto-offset-reset: earliest
kafka:
  product:
    name: post-topic


jwt:
  secret: ssssssssssssssssssssssssssmmmmmmmmmmmmmmm
  expiration: 25920000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uui}
server:
  port: 8081

logging:
  level:
    org.springframework.security: trace
    com.example.auth: info