spring:
  elasticsearch:
    cluster-name:
    rest:
      uris: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/post?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: post

jwt:
  secret: ssssssssssssssssssssssssssmmmmmmmmmmmmmmm
  expiration: 25920000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uui}
server:
  port: 8081

logging:
  level:
    org.springframework.security: trace
    com.example.auth: info