spring:
  elasticsearch:
    cluster-name:
    rest:
      uris: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/post?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


